name: Node.js CI

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: write

concurrency:
  group: "one"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
       repository: "imjac0b/${{ secrets.REPO1 }}"
       token: ${{ secrets.REPO1_TOKEN }}
    - uses: oven-sh/setup-bun@v2
    - run: bun i
    - run: bun run index.ts

  retrigger:
    name: Retrigger workflow
    runs-on: ubuntu-latest
    if: '${{ always() }}'
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Retrigger workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update Token
