name: Node.js CI

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
       repository: "imjac0b/${{ secrets.REPO1 }}"
       token: ${{ secrets.REPO1_TOKEN }}
    - uses: oven-sh/setup-bun@v2
    - run: bun i
    - run: bun run index.ts
