name: OWD-PAGE

on:
  schedule:
  - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: write

concurrency:
  group: "owd-page"
  cancel-in-progress: true

jobs:
  owd-page:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main Repo
      uses: actions/checkout@v4
      with:
        repository: "imjac0b/${{ secrets.OWD_REPO }}"
        token: ${{ secrets.OWD_TOKEN }}
        path: main-repo

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install Dependencies
      run: |
        cd main-repo
        bun i

    - name: Download Words File
      run: curl -L -o main-repo/words_alpha.txt https://github.com/dwyl/english-words/raw/refs/heads/master/words_alpha.txt

    - name: Run Script
      run: |
        cd main-repo
        mkdir -p available
        bun run index.ts page

    - name: Checkout Second Repo
      uses: actions/checkout@v4
      with:
        repository: "imjac0b/${{ secrets.OWD_RESULT_REPO }}"
        token: ${{ secrets.OWD_TOKEN }}
        path: result-repo

    - name: Copy Results
      run: |
        cp -r main-repo/available/* result-repo/

    - name: Commit and Push Changes
      run: |
        cd result-repo
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Update page domains"
          git push
        else
          echo "No changes to commit."
        fi

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2