name: OWD

on:
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write
  actions: write

concurrency:
  group: "owd"
  cancel-in-progress: true

jobs:
  owd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Repo
      uses: actions/checkout@v4
      with:
        repository: "imjac0b/${{ secrets.OWD_REPO }}"
        token: ${{ secrets.OWD_TOKEN }}
        path: main-repo

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install Dependencies
      run: |
        cd main-repo
        bun i

    - name: Download Words File
      run: curl -L -o main-repo/words_alpha.txt https://github.com/dwyl/english-words/raw/refs/heads/master/words_alpha.txt

    - name: Run Scripts
      run: |
        cd main-repo
        mkdir available
        bun run index.ts app & bun run index.ts dev & bun run index.ts day & bun run index.ts ing & bun run index.ts page & bun run index.ts new & bun run index.ts rsvp & bun run index.ts dad & bun run index.ts zip & bun run index.ts foo & bun run index.ts mov & bun run index.ts phd & bun run index.ts esq & bun run index.ts prof & bun run index.ts boo & bun run index.ts meme & bun run index.ts nexus & bun run index.ts how & bun run index.ts soy

    - name: Checkout Second Repo
      uses: actions/checkout@v4
      with:
        repository: "imjac0b/${{ secrets.OWD_RESULT_REPO }}"
        token: ${{ secrets.OWD_TOKEN }}
        path: result-repo

    - name: Copy Folder to Second Repo
      run: |
        cp -r main-repo/available/* result-repo/

    - name: Commit and Push Changes
      run: |
        cd result-repo
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Update"
          git push
        else
          echo "No changes to commit."
        fi

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
