name: OWD

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: write

concurrency:
  group: "owd"
  cancel-in-progress: true

jobs:
  check-tlds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tld:
          [
            com,
            dev,
            app,
            io,
            ai,
            xyz,
            org,
            me,
            net,
            tech,
            space,
            cloud,
            studio,
            sh,
            academy,
            accountants,
            actor,
            agency,
            airforce,
            apartments,
            archi,
            army,
            associates,
            attorney,
            auction,
            band,
            bargains,
            bet,
            bike,
            bingo,
            bio,
            black,
            blue,
            boutique,
            broker,
            builders,
            business,
            cab,
            cafe,
            camera,
            camp,
            capital,
            cards,
            care,
            careers,
            cash,
            casino,
            catering,
            center,
            chat,
            cheap,
            church,
            city,
            claims,
            cleaning,
            clinic,
            clothing,
            coach,
            codes,
            coffee,
            community,
            company,
            computer,
            condos,
            construction,
            consulting,
            contact,
            contractors,
            cool,
            coupons,
            credit,
            creditcard,
            cruises,
            dance,
            dating,
            deals,
            degree,
            delivery,
            democrat,
            dental,
            dentist,
            diamonds,
            digital,
            direct,
            directory,
            discount,
            doctor,
            dog,
            domains,
            education,
            email,
            energy,
            engineer,
            engineering,
            enterprises,
            equipment,
            estate,
            events,
            exchange,
            expert,
            exposed,
            express,
            fail,
            family,
            fan,
            farm,
            finance,
            financial,
            fish,
            fitness,
            flights,
            florist,
            football,
            forex,
            forsale,
            fund,
            furniture,
            futbol,
            fyi,
            gallery,
            games,
            gifts,
            glass,
            global,
            gmbh,
            gold,
            golf,
            graphics,
            gratis,
            green,
            gripe,
            group,
            guide,
            guru,
            haus,
            healthcare,
            hockey,
            holdings,
            holiday,
            hospital,
            house,
            immo,
            immobilien,
            industries,
            info,
            institute,
            insure,
            international,
            investments,
            irish,
            jetzt,
            jewelry,
            juegos,
            kaufen,
            kim,
            kitchen,
            land,
            lawyer,
            lease,
            legal,
            lgbt,
            life,
            lighting,
            limited,
            limo,
            live,
            llc,
            loans,
            ltd,
            maison,
            management,
            market,
            marketing,
            markets,
            mba,
            media,
            memorial,
            mobi,
            moda,
            money,
            mortgage,
            movie,
            navy,
            network,
            news,
            ninja,
            organic,
            partners,
            parts,
            pet,
            photography,
            photos,
            pictures,
            pink,
            pizza,
            place,
            plumbing,
            plus,
            poker,
            pro,
            productions,
            promo,
            properties,
            pub,
            recipes,
            red,
            rehab,
            reise,
            reisen,
            rentals,
            repair,
            report,
            republican,
            restaurant,
            reviews,
            rip,
            rocks,
            run,
            sale,
            salon,
            sarl,
            school,
            schule,
            services,
            shiksha,
            shoes,
            shopping,
            show,
            singles,
            ski,
            soccer,
            social,
            software,
            solar,
            solutions,
            style,
            supplies,
            supply,
            support,
            surgery,
            systems,
            tax,
            taxi,
            team,
            technology,
            tennis,
            theater,
            tienda,
            tips,
            tires,
            today,
            tools,
            tours,
            town,
            toys,
            trading,
            training,
            university,
            vacations,
            ventures,
            vet,
            viajes,
            video,
            villas,
            vin,
            vision,
            vote,
            voto,
            voyage,
            watch,
            watches,
            wine,
            works,
            world,
            wtf,
            xn--5tzm5g,
            xn--6frz82g,
            xn--czrs0t,
            xn--fjq720a,
            xn--unup4y,
            xn--vhquv,
            zone,
            ac,
            accountant,
            adult,
            ag,
            art,
            asia,
            audio,
            auto,
            autos,
            baby,
            bar,
            bayern,
            beauty,
            beer,
            best,
            bid,
            biz,
            blackfriday,
            blog,
            boats,
            bond,
            boston,
            br.com,
            build,
            buzz,
            bz,
            cam,
            car,
            cars,
            casa,
            cc,
            ceo,
            cfd,
            channel,
            charity,
            christmas,
            click,
            club,
            cn.com,
            co,
            co.com,
            co.nz,
            college,
            com.co,
            com.mx,
            com.tw,
            cooking,
            country,
            courses,
            cricket,
            dad,
            date,
            de.com,
            dealer,
            design,
            diet,
            diy,
            download,
            earth,
            ec,
            esq,
            eu.com,
            eus,
            faith,
            fans,
            fashion,
            feedback,
            film,
            fishing,
            fit,
            flowers,
            fm,
            foo,
            food,
            forum,
            foundation,
            fun,
            game,
            garden,
            gent,
            gift,
            gives,
            giving,
            gr.com,
            gs,
            guitars,
            hair,
            hamburg,
            help,
            hiphop,
            hiv,
            hn,
            homes,
            horse,
            host,
            hosting,
            how,
            icu,
            inc,
            ing,
            ink,
            jobs,
            jpn.com,
            kids,
            kiwi,
            lat,
            lifestyle,
            link,
            living,
            loan,
            lol,
            london,
            love,
            ltda,
            luxe,
            luxury,
            makeup,
            melbourne,
            meme,
            men,
            menu,
            miami,
            mn,
            moe,
            mom,
            monster,
            motorcycles,
            mov,
            mx,
            nagoya,
            name,
            new,
            nexus,
            ngo,
            nz,
            observer,
            okinawa,
            one,
            ong,
            onl,
            online,
            ooo,
            osaka,
            page,
            paris,
            party,
            phd,
            photo,
            pics,
            porn,
            press,
            prof,
            property,
            pw,
            qpon,
            quest,
            racing,
            radio.am,
            radio.fm,
            realty,
            rent,
            rest,
            review,
            rich,
            rodeo,
            ru.com,
            ryukyu,
            sa.com,
            sbs,
            sc,
            science,
            se.net,
            sex,
            sexy,
            shop,
            site,
            skin,
            soy,
            srl,
            storage,
            store,
            stream,
            study,
            surf,
            sydney,
            tattoo,
            tel,
            theatre,
            tickets,
            tokyo,
            top,
            trade,
            tube,
            tv,
            tw,
            uk,
            uk.com,
            uk.net,
            uno,
            us.com,
            vana,
            vc,
            vegas,
            vip,
            vodka,
            voting,
            webcam,
            website,
            wedding,
            wiki,
            win,
            work,
            xn--3ds443g,
            xn--80asehdb,
            xn--80aswg,
            xn--9dbq2a,
            xn--e1a4c,
            xn--fiq228c5hs,
            xn--mk1bu44c,
            xn--ngbc5azd,
            xn--q9jyb4c,
            xn--t60b56a,
            xn--tckwe,
            yachts,
            yoga,
            yokohama,
            za.com,
            zip,
            am,
            be,
            cl,
            cm,
            cx,
            gy,
            im,
            la,
            li,
            my,
            net.nz,
            org.nz,
            pl,
            tl,
            ws,
          ]
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4
        with:
          repository: "imjac0b/${{ secrets.OWD_REPO }}"
          token: ${{ secrets.OWD_TOKEN }}
          path: main-repo

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: |
          cd main-repo
          bun i

      - name: Download Words File
        run: curl -L -o main-repo/words_alpha.txt https://github.com/dwyl/english-words/raw/refs/heads/master/words_alpha.txt

      - name: Run Script without DNS
        run: |
          cd main-repo
          bun check --tld ${{ matrix.tld }}

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tld }}.txt
          path: main-repo/available/${{ matrix.tld }}.txt
          retention-days: 1

  check-prefix-tlds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tld: [com]
        prefix: [get, my, use, try, go, the, buy]
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4
        with:
          repository: "imjac0b/${{ secrets.OWD_REPO }}"
          token: ${{ secrets.OWD_TOKEN }}
          path: main-repo

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: |
          cd main-repo
          bun i

      - name: Download Words File
        run: curl -L -o main-repo/words_alpha.txt https://github.com/dwyl/english-words/raw/refs/heads/master/words_alpha.txt

      - name: Run Script with Prefix
        run: |
          cd main-repo
          bun check --tld ${{ matrix.tld }} --prefix ${{ matrix.prefix }}

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: prefix-${{ matrix.prefix }}-${{ matrix.tld }}.txt
          path: main-repo/available/prefix/${{ matrix.prefix }}/${{ matrix.tld }}.txt
          retention-days: 1

  check-suffix-tlds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tld: [com]
        suffix: [app, hub, lab, hq, ai, box, now, api, gpt]
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4
        with:
          repository: "imjac0b/${{ secrets.OWD_REPO }}"
          token: ${{ secrets.OWD_TOKEN }}
          path: main-repo

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: |
          cd main-repo
          bun i

      - name: Download Words File
        run: curl -L -o main-repo/words_alpha.txt https://github.com/dwyl/english-words/raw/refs/heads/master/words_alpha.txt

      - name: Run Script with Suffix
        run: |
          cd main-repo
          bun check --tld ${{ matrix.tld }} --suffix ${{ matrix.suffix }}

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: suffix-${{ matrix.suffix }}-${{ matrix.tld }}.txt
          path: main-repo/available/suffix/${{ matrix.suffix }}/${{ matrix.tld }}.txt
          retention-days: 1

  push-results:
    needs: [check-tlds, check-prefix-tlds, check-suffix-tlds]
    runs-on: ubuntu-latest
    steps:
      - name: Download All Results
        uses: actions/download-artifact@v4
        with:
          path: all-results

      - name: Organize Results and Copy to Repo
        run: |
          mkdir -p result-repo
          echo "Organizing downloaded artifacts..."
          # Loop through each downloaded artifact directory (named after the artifact)
          for artifact_dir in all-results/*; do
            if [ -d "$artifact_dir" ]; then
              echo "Processing artifact directory: $artifact_dir"
              # The actual result file is inside this directory
              find "$artifact_dir" -type f -name "*.txt" -print0 | while IFS= read -r -d $'\0' file; do
                artifact_name=$(basename "$artifact_dir") # e.g., prefix-try-com.txt or com.txt
                echo "  Found file: $file with artifact name: $artifact_name"

                # Reconstruct the target path based on the artifact name
                if [[ "$artifact_name" == prefix-*-* ]]; then
                  # Extract prefix and tld: prefix-<prefix>-<tld>.txt
                  target_path=$(echo "$artifact_name" | sed -E 's/^prefix-([^-]+)-(.+)\.txt$/prefix\/\1\/\2.txt/')
                elif [[ "$artifact_name" == suffix-*-* ]]; then
                   # Extract suffix and tld: suffix-<suffix>-<tld>.txt
                  target_path=$(echo "$artifact_name" | sed -E 's/^suffix-([^-]+)-(.+)\.txt$/suffix\/\1\/\2.txt/')
                else
                  # Simple TLD file, goes to root
                  target_path="$artifact_name"
                fi

                target_dir=$(dirname "$target_path")
                target_file_path="result-repo/$target_path"
                echo "  Determined target path: $target_file_path"

                # Create target directory structure in result-repo if it doesn't exist
                if [[ "$target_dir" != "." ]]; then
                  mkdir -p "result-repo/$target_dir"
                  echo "  Ensured directory exists: result-repo/$target_dir"
                fi

                # Move the file to the correct location in result-repo
                mv "$file" "$target_file_path"
                echo "  Moved file to $target_file_path"
              done
            else
              echo "Skipping non-directory item: $artifact_dir"
            fi
          done
          echo "Finished organizing artifacts."
          # Clean up the download directory
          rm -rf all-results

      - name: Generate Files List
        run: |
          cd result-repo
          # Define the output file path without .txt
          output_file="metadata/files"
          # Create the metadata directory if it doesn't exist
          mkdir -p "$(dirname "$output_file")"
          # Find all .txt files, print relative paths, sort them, and save to the file
          # Exclude the output file itself from the list
          # Note: We still FIND *.txt files, but EXCLUDE the specific path ./metadata/files
          find . -name "*.txt" -not -path "./$output_file" | sed 's|^\./||' | sort > "$output_file"
          echo "Generated $output_file"

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy result-repo --project-name=${{ secrets.OWD_CF_PROJECT }}
