name: OWD

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: write

concurrency:
  group: "owd"
  cancel-in-progress: true

jobs:
  # check-tlds:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       tld: [app, boo, day, dev, how, ing, meme, mov, new, page, zip]
  #   steps:
  #     - name: Checkout Main Repo
  #       uses: actions/checkout@v4
  #       with:
  #         repository: "imjac0b/${{ secrets.OWD_REPO }}"
  #         token: ${{ secrets.OWD_TOKEN }}
  #         path: main-repo

  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v2

  #     - name: Install Dependencies
  #       run: |
  #         cd main-repo
  #         bun i

  #     - name: Download Words File
  #       run: curl -L -o main-repo/words_alpha.txt https://github.com/dwyl/english-words/raw/refs/heads/master/words_alpha.txt

  #     - name: Run Script without DNS
  #       run: |
  #         cd main-repo
  #         bun check --tld ${{ matrix.tld }}

  #     - name: Upload Results
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ${{ matrix.tld }}.txt
  #         path: main-repo/available/${{ matrix.tld }}.txt
  #         retention-days: 1

  check-dns-tlds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tld:
          [
            com,
            ai,
            io,
            co,
            xyz,
            so,
            sh,
            link,
            gg,
            me,
            run,
            net,
            org,
            venture,
            capital,
            live,
            new,
            asia,
            tech,
            inc,
            vc,
            ly,
            studio,
            design,
            club,
            money,
            online,
            cloud,
            agency,
            wtf,
            chat,
            tv,
            bio,
            site,
            art,
            shop,
            domains,
            blog,
            finance,
            work,
            email,
            fm,
            page,
            travel,
            top,
            info,
            network,
            win,
            ltd,
            vip,
            biz,
            games,
            help,
            video,
            guide,
          ]
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4
        with:
          repository: "imjac0b/${{ secrets.OWD_REPO }}"
          token: ${{ secrets.OWD_TOKEN }}
          path: main-repo

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: |
          cd main-repo
          bun i

      - name: Download Words File
        run: curl -L -o main-repo/words_alpha.txt https://github.com/dwyl/english-words/raw/refs/heads/master/words_alpha.txt

      - name: Run Script with DNS
        run: |
          cd main-repo
          bun check --tld ${{ matrix.tld }} --dns

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tld }}.txt
          path: main-repo/available/${{ matrix.tld }}.txt
          retention-days: 1

  check-prefix-tlds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tld: [com]
        prefix: [get, my, use, try, go, the, buy]
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4
        with:
          repository: "imjac0b/${{ secrets.OWD_REPO }}"
          token: ${{ secrets.OWD_TOKEN }}
          path: main-repo

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: |
          cd main-repo
          bun i

      - name: Download Words File
        run: curl -L -o main-repo/words_alpha.txt https://github.com/dwyl/english-words/raw/refs/heads/master/words_alpha.txt

      - name: Run Script with Prefix
        run: |
          cd main-repo
          bun check --tld ${{ matrix.tld }} --dns --prefix ${{ matrix.prefix }}

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: prefix-${{ matrix.prefix }}-${{ matrix.tld }}.txt
          path: main-repo/available/prefix/${{ matrix.prefix }}/${{ matrix.tld }}.txt
          retention-days: 1

  check-suffix-tlds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tld: [com]
        suffix: [app, hub, lab, hq, ai, box, now, api, gpt]
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4
        with:
          repository: "imjac0b/${{ secrets.OWD_REPO }}"
          token: ${{ secrets.OWD_TOKEN }}
          path: main-repo

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: |
          cd main-repo
          bun i

      - name: Download Words File
        run: curl -L -o main-repo/words_alpha.txt https://github.com/dwyl/english-words/raw/refs/heads/master/words_alpha.txt

      - name: Run Script with Suffix
        run: |
          cd main-repo
          bun check --tld ${{ matrix.tld }} --dns --suffix ${{ matrix.suffix }}

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: suffix-${{ matrix.suffix }}-${{ matrix.tld }}.txt
          path: main-repo/available/suffix/${{ matrix.suffix }}/${{ matrix.tld }}.txt
          retention-days: 1

  push-results:
    needs: [check-dns-tlds, check-prefix-tlds, check-suffix-tlds]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Result Repo
        uses: actions/checkout@v4
        with:
          repository: "imjac0b/${{ secrets.OWD_RESULT_REPO }}"
          token: ${{ secrets.OWD_TOKEN }}
          path: result-repo

      - name: Download All Results
        uses: actions/download-artifact@v4
        with:
          path: all-results # Download all artifacts into this directory

      - name: Organize Results and Copy to Repo
        run: |
          echo "Organizing downloaded artifacts..."
          # Loop through each downloaded artifact directory (named after the artifact)
          for artifact_dir in all-results/*; do
            if [ -d "$artifact_dir" ]; then
              echo "Processing artifact directory: $artifact_dir"
              # The actual result file is inside this directory
              find "$artifact_dir" -type f -name "*.txt" -print0 | while IFS= read -r -d $'\0' file; do
                artifact_name=$(basename "$artifact_dir") # e.g., prefix-try-com.txt or com.txt
                echo "  Found file: $file with artifact name: $artifact_name"

                # Reconstruct the target path based on the artifact name
                if [[ "$artifact_name" == prefix-*-* ]]; then
                  # Extract prefix and tld: prefix-<prefix>-<tld>.txt
                  target_path=$(echo "$artifact_name" | sed -E 's/^prefix-([^-]+)-(.+)\.txt$/prefix\/\1\/\2.txt/')
                elif [[ "$artifact_name" == suffix-*-* ]]; then
                   # Extract suffix and tld: suffix-<suffix>-<tld>.txt
                  target_path=$(echo "$artifact_name" | sed -E 's/^suffix-([^-]+)-(.+)\.txt$/suffix\/\1\/\2.txt/')
                else
                  # Simple TLD file, goes to root
                  target_path="$artifact_name"
                fi

                target_dir=$(dirname "$target_path")
                target_file_path="result-repo/$target_path"
                echo "  Determined target path: $target_file_path"

                # Create target directory structure in result-repo if it doesn't exist
                if [[ "$target_dir" != "." ]]; then
                  mkdir -p "result-repo/$target_dir"
                  echo "  Ensured directory exists: result-repo/$target_dir"
                fi

                # Move the file to the correct location in result-repo
                mv "$file" "$target_file_path"
                echo "  Moved file to $target_file_path"
              done
            else
              echo "Skipping non-directory item: $artifact_dir"
            fi
          done
          echo "Finished organizing artifacts."
          # Clean up the download directory
          rm -rf all-results

      - name: Generate Files List
        run: |
          cd result-repo
          # Find all .txt files, print relative paths, sort them, and save to files.txt
          # Exclude files.txt itself from the list
          find . -name "*.txt" -not -name "files.txt" | sed 's|^\./||' | sort > files.txt
          echo "Generated files.txt"

      - name: Commit and Push Changes
        run: |
          cd result-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . # This will now include files.txt
          # Check if there are changes staged
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update domains"
            git push
          fi

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
