name: Project 1

on:
  schedule:
  - cron: "*/5 * * * *"

  workflow_dispatch:

concurrency:
  group: "project-1"
  cancel-in-progress: true

jobs:
  owd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Repo
      uses: actions/checkout@v4
      with:
        repository: "imjac0b/${{ secrets.PROJECT_1_REPO }}"
        token: ${{ secrets.PROJECT_1_TOKEN }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install Dependencies
      run: bun i
      
    - name: Run Scripts
      run: bun run index.ts

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
