name: Project 6

on:
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:

concurrency:
  group: "project-6"
  cancel-in-progress: true

jobs:
  project1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Repo
      uses: actions/checkout@v4
      with:
        repository: "imjac0b/${{ secrets.PROJECT_6_REPO }}"
        token: ${{ secrets.PROJECT_6_TOKEN }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install Dependencies
      run: bun i
      
    - name: Run Scripts
      run: bun run index.ts
